[package]
name = "yew-app"
version = "0.1.0"
authors = ["Taylor Fraley <tfraley@clearent.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17.4"
wasm-bindgen = "0.2.74"
stdweb = "0.4.20"
